---
- hosts: all
  become: True
  tasks:
    # replace include with include tasks. include is deprecated.
    - include_tasks: tasks/deps.yml

    # your code goes here ...
    - include_tasks: tasks/application.yml
    - include_tasks: tasks/runit.yml
    - include_tasks: tasks/nginx.yml
